name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC_INSTANCE_IP }} << EOF
            source ~/.bashrc
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin"
            cd chat-backend/
            bash deploy/deploy.sh
          EOF